//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloneDetective.CloneReporting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloneDetective.CloneReporting.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clone report &quot;{0}&quot; could not be loaded: {1}.
        /// </summary>
        internal static string CannotLoadCloneReport {
            get {
                return ResourceManager.GetString("CannotLoadCloneReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start Clone Detective while it is still running..
        /// </summary>
        internal static string CloneDetectiveAlreadyRunning {
            get {
                return ResourceManager.GetString("CloneDetectiveAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://conqat.cs.tum.edu/ns/clonereport&quot; xmlns:mstns=&quot;http://conqat.cs.tum.edu/ns/clonereport&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;http://conqat.cs.tum.edu/ns/clonereport&quot;&gt;
        ///  &lt;xs:element name=&quot;cloneReport&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot; name=&quot;sourceFile&quot;&gt;
        ///          &lt;xs:compl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CloneReportSchema {
            get {
                return ResourceManager.GetString("CloneReportSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://conqat.cs.tum.edu/ns/clonereport.
        /// </summary>
        internal static string CloneReportSchemaNamespace {
            get {
                return ResourceManager.GetString("CloneReportSchemaNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Detective did not produce a clone report. Please review the log file..
        /// </summary>
        internal static string ConqatDidNotProduceCloneReport {
            get {
                return ResourceManager.GetString("ConqatDidNotProduceCloneReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although the file &quot;{0}&quot; is a well-formed XML document it is not valid clone report. See list of errors below.
        ///{1}.
        /// </summary>
        internal static string InvalidCloneReport {
            get {
                return ResourceManager.GetString("InvalidCloneReport", resourceCulture);
            }
        }
    }
}
