//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloneDetective.Package {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloneDetective.Package.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CannotCreateWindow {
            get {
                return ResourceManager.GetString("CannotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Information.
        /// </summary>
        internal static string CategoryCloneInformation {
            get {
                return ResourceManager.GetString("CategoryCloneInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Class {0}.
        /// </summary>
        internal static string CloneClassName {
            get {
                return ResourceManager.GetString("CloneClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Detective.
        /// </summary>
        internal static string CloneDetective {
            get {
                return ResourceManager.GetString("CloneDetective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string CloneExplorerFailed {
            get {
                return ResourceManager.GetString("CloneExplorerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory: {0}.
        /// </summary>
        internal static string CloneExplorerMemoryStatistic {
            get {
                return ResourceManager.GetString("CloneExplorerMemoryStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string CloneExplorerStopped {
            get {
                return ResourceManager.GetString("CloneExplorerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        internal static string CloneExplorerSucceeded {
            get {
                return ResourceManager.GetString("CloneExplorerSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0}.
        /// </summary>
        internal static string CloneExplorerTimeStatistic {
            get {
                return ResourceManager.GetString("CloneExplorerTimeStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Explorer.
        /// </summary>
        internal static string CloneExplorerToolWindowTitle {
            get {
                return ResourceManager.GetString("CloneExplorerToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone File Summary.
        /// </summary>
        internal static string CloneFileSummary {
            get {
                return ResourceManager.GetString("CloneFileSummary", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CloneIntersections {
            get {
                object obj = ResourceManager.GetObject("CloneIntersections", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Intersections.
        /// </summary>
        internal static string CloneIntersectionsToolWindowTitle {
            get {
                return ResourceManager.GetString("CloneIntersectionsToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Intersection Summary.
        /// </summary>
        internal static string CloneIntersectionSummary {
            get {
                return ResourceManager.GetString("CloneIntersectionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Results.
        /// </summary>
        internal static string CloneResultsToolWindowTitle {
            get {
                return ResourceManager.GetString("CloneResultsToolWindowTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CloseResults {
            get {
                object obj = ResourceManager.GetObject("CloseResults", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Clones.
        /// </summary>
        internal static string CommandFindClones {
            get {
                return ResourceManager.GetString("CommandFindClones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Clone Intersections.
        /// </summary>
        internal static string CommandShowCloneIntersections {
            get {
                return ResourceManager.GetString("CommandShowCloneIntersections", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CSharpFile {
            get {
                object obj = ResourceManager.GetObject("CSharpFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Intersections.
        /// </summary>
        internal static string DisplayNameCloneIntersections {
            get {
                return ResourceManager.GetString("DisplayNameCloneIntersections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Percentage.
        /// </summary>
        internal static string DisplayNameClonePercentage {
            get {
                return ResourceManager.GetString("DisplayNameClonePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Path.
        /// </summary>
        internal static string DisplayNameFullPath {
            get {
                return ResourceManager.GetString("DisplayNameFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DisplayNameName {
            get {
                return ResourceManager.GetString("DisplayNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Cloned Lines.
        /// </summary>
        internal static string DisplayNameNumberOfClonedLines {
            get {
                return ResourceManager.GetString("DisplayNameNumberOfClonedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Clones.
        /// </summary>
        internal static string DisplayNameNumberOfClones {
            get {
                return ResourceManager.GetString("DisplayNameNumberOfClones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Clone Classes.
        /// </summary>
        internal static string DisplayNumberOfCloneClasses {
            get {
                return ResourceManager.GetString("DisplayNumberOfCloneClasses", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid file name..
        /// </summary>
        internal static string FileNameCannotBeBlank {
            get {
                return ResourceManager.GetString("FileNameCannotBeBlank", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FolderClosed {
            get {
                object obj = ResourceManager.GetObject("FolderClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderOpened {
            get {
                object obj = ResourceManager.GetObject("FolderOpened", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapping would map the file &quot;{0}&quot; to &quot;{1}&quot; which does not exist. Please correct the mapping..
        /// </summary>
        internal static string ImportCloneReportIncorrectMapping {
            get {
                return ResourceManager.GetString("ImportCloneReportIncorrectMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select local folder for &quot;{0}&quot;:.
        /// </summary>
        internal static string ImportCloneReportSelectFolder {
            get {
                return ResourceManager.GetString("ImportCloneReportSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to ConQAT is either invalid or has not been configured yet. Please configure it under Tools -&gt; Options -&gt; Clone Detective -&gt; Settings..
        /// </summary>
        internal static string InvalidConqatBatPath {
            get {
                return ResourceManager.GetString("InvalidConqatBatPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Java Home directory is either invalid or has not been configured yet. Please configure it under Tools -&gt; Options -&gt; Clone Detective -&gt; Settings..
        /// </summary>
        internal static string InvalidJavaExePath {
            get {
                return ResourceManager.GetString("InvalidJavaExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string {0} is not a valid macro. For a list of valid macros please look at the online help..
        /// </summary>
        internal static string InvalidMacro {
            get {
                return ResourceManager.GetString("InvalidMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} b.
        /// </summary>
        internal static string MemoryBytes {
            get {
                return ResourceManager.GetString("MemoryBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} gb.
        /// </summary>
        internal static string MemoryGigaBytes {
            get {
                return ResourceManager.GetString("MemoryGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} kb.
        /// </summary>
        internal static string MemoryKiloBytes {
            get {
                return ResourceManager.GetString("MemoryKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} mb.
        /// </summary>
        internal static string MemoryMegaBytes {
            get {
                return ResourceManager.GetString("MemoryMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Class {0}; Lines {1} - {2}.
        /// </summary>
        internal static string MenuClone {
            get {
                return ResourceManager.GetString("MenuClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all Occurrences.
        /// </summary>
        internal static string MenuFindAllOccurrences {
            get {
                return ResourceManager.GetString("MenuFindAllOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Code Editor.
        /// </summary>
        internal static string MenuOpenInEditor {
            get {
                return ResourceManager.GetString("MenuOpenInEditor", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NewParameter {
            get {
                object obj = ResourceManager.GetObject("NewParameter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No clone report loaded or no file selected..
        /// </summary>
        internal static string NoCloneReportOrNoFileSelected {
            get {
                return ResourceManager.GetString("NoCloneReportOrNoFileSelected", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ====== Clone detection failed ======.
        /// </summary>
        internal static string OutputFooterFailed {
            get {
                return ResourceManager.GetString("OutputFooterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ====== Clone detection stopped ======.
        /// </summary>
        internal static string OutputFooterStopped {
            get {
                return ResourceManager.GetString("OutputFooterStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ====== Clone detection succeeded ======.
        /// </summary>
        internal static string OutputFooterSucceeded {
            get {
                return ResourceManager.GetString("OutputFooterSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------ Clone detection started ------.
        /// </summary>
        internal static string OutputHeaderStarted {
            get {
                return ResourceManager.GetString("OutputHeaderStarted", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Parameter {
            get {
                object obj = ResourceManager.GetObject("Parameter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Properties {
            get {
                object obj = ResourceManager.GetObject("Properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} already overridden above. Remove one entry in this list..
        /// </summary>
        internal static string PropertyAlreadyOverridden {
            get {
                return ResourceManager.GetString("PropertyAlreadyOverridden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} cannot be overriden because the analysis file does not contain such a property..
        /// </summary>
        internal static string PropertyCannotBeOverridden {
            get {
                return ResourceManager.GetString("PropertyCannotBeOverridden", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Run {
            get {
                object obj = ResourceManager.GetObject("Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Running {
            get {
                object obj = ResourceManager.GetObject("Running", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Solution {
            get {
                object obj = ResourceManager.GetObject("Solution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stopped {
            get {
                object obj = ResourceManager.GetObject("Stopped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Succeeded {
            get {
                object obj = ResourceManager.GetObject("Succeeded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} d.
        /// </summary>
        internal static string TimeDays {
            get {
                return ResourceManager.GetString("TimeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} h.
        /// </summary>
        internal static string TimeHours {
            get {
                return ResourceManager.GetString("TimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} ms.
        /// </summary>
        internal static string TimeMilliseconds {
            get {
                return ResourceManager.GetString("TimeMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} m.
        /// </summary>
        internal static string TimeMinutes {
            get {
                return ResourceManager.GetString("TimeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} s.
        /// </summary>
        internal static string TimeSeconds {
            get {
                return ResourceManager.GetString("TimeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled case label &quot;{0}&quot;..
        /// </summary>
        internal static string UnhandledCaseLabel {
            get {
                return ResourceManager.GetString("UnhandledCaseLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can save the changes you have to fix all errors first..
        /// </summary>
        internal static string YouMustFixAllErrors {
            get {
                return ResourceManager.GetString("YouMustFixAllErrors", resourceCulture);
            }
        }
    }
}
